name: Build and Release iOS FFmpeg-kit

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - development

jobs:
  build-and-release-ios:
    name: Build and Release iOS xcframework
    runs-on: macos-14
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Prerequisites
        run: brew install autoconf automake libtool pkg-config curl git cmake nasm
        
      - name: Set up Xcode
        run: echo "export DEVELOPER_DIR=/Applications/Xcode_15.4.app/Contents/Developer" > ~/.xcode.for.ffmpeg.kit.sh
        
      - name: Build iOS xcframework (full-gpl)
        run: ./ios.sh --xcframework --enable-ios-audiotoolbox --enable-ios-avfoundation --enable-ios-bzip2 --enable-ios-libiconv --enable-ios-videotoolbox --enable-ios-zlib --enable-gpl --enable-x264
        
      - name: Print build logs
        if: ${{ always() }}
        run: cat build.log
        
      - name: Create release package
        run: |
          mkdir -p release
          # Find and copy the built xcframeworks
          find . -name "*.xcframework" -type d -exec cp -r {} release/ \;
          cd release
          zip -r ffmpeg-kit-full-gpl-6.0-ios-xcframework.zip *.xcframework
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-kit-ios-xcframework
          path: release/ffmpeg-kit-full-gpl-6.0-ios-xcframework.zip
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: v6.0-custom-${{ github.sha }}
          name: FFmpeg-kit iOS v6.0 Custom Build
          files: release/ffmpeg-kit-full-gpl-6.0-ios-xcframework.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}